### PR TITLE
Add status section

### PR DESCRIPTION
**Pull request by jorgeazevedo**
Prout has a bunch of useful information available to facilitate debugging issues, but without a mention on the README it can be quite difficult to find!

### CODE REVIEW

**Comment by jorgeazevedo** [comment]
Oh no, I've awaken this project from it's slumber!
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-10-16
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```

**Comment by rtyley** [comment]
I've applied c1c35a40aab5 to master to fix the JDK used by Travis ([we don't want to ever be using the Oracle JDK now, just the OpenJDK](https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html)), and rebased this branch on top of it - hopefully this branch should build now!

**Comment by rtyley** [comment]
It did pass, as it should!

**Comment by jorgeazevedo** [comment]
Thanks Roberto!

**Pull request merged**
